### ISSUE TITLE
 “Deploy to Heroku” button无法使用

### ISSUE THREAD

**Issue by MrLiuMoore** [qkqpttgf/OfficeAdmin#4]
使用 “Deploy to Heroku”后出现这样的错误提示
![wrong](https://s1.328888.xyz/2022/02/11/GG3bg.png)
`Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.`

**Comment by qkqpttgf** [comment]
那我的删除线白画了呗？删除线是啥意思知道不？

**Comment by qkqpttgf** [comment]
哦，看错项目了……
好吧，这个项目也被标记了～～
