### ISSUE TITLE
希望完善文档，以及增加Vercel和Replit部署

### ISSUE THREAD

**Issue by zysord** [qkqpttgf/OfficeAdmin#6]
希望完善officeadmin的README文档中的云函数部署教程，增加Vercel和Replit部署。
😊😊😊

**Comment by qkqpttgf** [comment]
Vercel可以部署的，教程就不用了，跟OneManager一样
Replit还没弄，但你可以直接把那边的platform/Replit.php复制过来用应该就可以了，直接在Replit后台编辑新增文件。

**Comment by telnetpig** [comment]
能否增加Vercel部署教程

**Comment by qkqpttgf** [comment]
> 能否增加Vercel部署教程

要啥教程，会部署OneManager不就会了。

**Comment by woshichenghaibo** [comment]
这个是干嘛的？怎么没有介绍
